"""primera 15/12

Revision ID: 181729c10303
Revises: 9f85cf890246
Create Date: 2025-12-15 15:10:13.263661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '181729c10303'
down_revision: Union[str, None] = '9f85cf890246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actividades', sa.Column('tipo', sa.Enum('ALIMENTACION', 'HIGIENE', 'APRENDIZAJE', 'FOTO', 'ANIMO', 'SIESTA', 'LOGROS', 'OBSERVACION', 'SALUD', 'VIDEO', 'MEDICAMENTO', 'ACCIDENTE', 'TAREA', name='tipoactividad'), nullable=False))
    op.add_column('actividades', sa.Column('valor', sa.String(length=100), nullable=True))
    op.add_column('actividades', sa.Column('hora', sa.String(length=10), nullable=True))
    
