"""primera 16/12

Revision ID: 30ccbd5122b9
Revises: 181729c10303
Create Date: 2025-12-17 08:53:05.768296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '30ccbd5122b9'
down_revision: Union[str, None] = '181729c10303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planificaciones_profesoras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profesora_id', sa.Integer(), nullable=False),
    sa.Column('duracion', sa.Enum('MES_1', 'MES_3', 'MES_6', 'GESTION', name='duracionplanificacion'), nullable=False),
    sa.Column('archivo_url', sa.String(length=255), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profesora_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    