"""esquema de inicio

Revision ID: 5d5feb40d62b
Revises: 
Create Date: 2025-10-28 15:55:04.916976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d5feb40d62b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_pago',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_pago_nombre'), 'categorias_pago', ['nombre'], unique=True)
    op.create_table('familias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_familias_nombre'), 'familias', ['nombre'], unique=True)
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horarios_nombre'), 'horarios', ['nombre'], unique=False)
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vista', sa.String(length=80), nullable=False),
    sa.Column('accion', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permisos_accion'), 'permisos', ['accion'], unique=False)
    op.create_index(op.f('ix_permisos_vista'), 'permisos', ['vista'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_nombre'), 'roles', ['nombre'], unique=True)
    op.create_table('sedes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('direccion', sa.String(length=250), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sedes_codigo'), 'sedes', ['codigo'], unique=True)
    op.create_table('tokens_revocados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('revocado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_revocados_jti'), 'tokens_revocados', ['jti'], unique=True)
    op.create_index(op.f('ix_tokens_revocados_tipo'), 'tokens_revocados', ['tipo'], unique=False)
    op.create_table('turnos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turnos_nombre'), 'turnos', ['nombre'], unique=True)
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('familia_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['familia_id'], ['familias.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_familia_id'), 'categorias', ['familia_id'], unique=False)
    op.create_index(op.f('ix_categorias_nombre'), 'categorias', ['nombre'], unique=False)
    op.create_table('cursos_extra',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('instructor', sa.String(length=120), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('precio_interno', sa.Numeric(precision=10, scale=2), nullable=False, comment='Precio para alumnos regulares del jardín'),
    sa.Column('precio_externo', sa.Numeric(precision=10, scale=2), nullable=False, comment='Precio para alumnos nuevos solo de curso extra'),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cursos_extra_nombre'), 'cursos_extra', ['nombre'], unique=False)
    op.create_index(op.f('ix_cursos_extra_sede_id'), 'cursos_extra', ['sede_id'], unique=False)
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('gestion', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sede_id', 'nombre', 'gestion', name='uq_grupo_sede_gestion')
    )
    op.create_index(op.f('ix_grupos_activo'), 'grupos', ['activo'], unique=False)
    op.create_index(op.f('ix_grupos_gestion'), 'grupos', ['gestion'], unique=False)
    op.create_index(op.f('ix_grupos_nombre'), 'grupos', ['nombre'], unique=False)
    op.create_index(op.f('ix_grupos_sede_id'), 'grupos', ['sede_id'], unique=False)
    op.create_table('precios_turnos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.Column('categoria_pago_id', sa.Integer(), nullable=False),
    sa.Column('gestion', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_pago_id'], ['categorias_pago.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turno_id', 'categoria_pago_id', 'gestion', name='uq_turno_categoria_gestion')
    )
    op.create_index(op.f('ix_precios_turnos_categoria_pago_id'), 'precios_turnos', ['categoria_pago_id'], unique=False)
    op.create_index(op.f('ix_precios_turnos_gestion'), 'precios_turnos', ['gestion'], unique=False)
    op.create_index(op.f('ix_precios_turnos_turno_id'), 'precios_turnos', ['turno_id'], unique=False)
    op.create_table('roles_permisos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.Column('asignado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol_id', 'permiso_id', name='uq_rol_permiso')
    )
    op.create_index(op.f('ix_roles_permisos_permiso_id'), 'roles_permisos', ['permiso_id'], unique=False)
    op.create_index(op.f('ix_roles_permisos_rol_id'), 'roles_permisos', ['rol_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hash_password', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('foto_perfil_url', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=False)
    op.create_index(op.f('ix_usuarios_sede_id'), 'usuarios', ['sede_id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('alumnos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=True),
    sa.Column('nombres', sa.String(length=120), nullable=False),
    sa.Column('apellidos', sa.String(length=120), nullable=False),
    sa.Column('documento', sa.String(length=30), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tutor_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumnos_activo'), 'alumnos', ['activo'], unique=False)
    op.create_index(op.f('ix_alumnos_apellidos'), 'alumnos', ['apellidos'], unique=False)
    op.create_index(op.f('ix_alumnos_codigo'), 'alumnos', ['codigo'], unique=True)
    op.create_index(op.f('ix_alumnos_documento'), 'alumnos', ['documento'], unique=False)
    op.create_index(op.f('ix_alumnos_fecha_nacimiento'), 'alumnos', ['fecha_nacimiento'], unique=False)
    op.create_index(op.f('ix_alumnos_nombres'), 'alumnos', ['nombres'], unique=False)
    op.create_index(op.f('ix_alumnos_sede_id'), 'alumnos', ['sede_id'], unique=False)
    op.create_index(op.f('ix_alumnos_tutor_id'), 'alumnos', ['tutor_id'], unique=False)
    op.create_table('arqueos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('saldo_inicial', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_ingresos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_egresos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('saldo_final', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(length=255), nullable=True),
    sa.Column('elaborado_por', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['elaborado_por'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arqueos_anio'), 'arqueos', ['anio'], unique=False)
    op.create_index(op.f('ix_arqueos_elaborado_por'), 'arqueos', ['elaborado_por'], unique=False)
    op.create_index(op.f('ix_arqueos_mes'), 'arqueos', ['mes'], unique=False)
    op.create_index(op.f('ix_arqueos_sede_id'), 'arqueos', ['sede_id'], unique=False)
    op.create_table('asistencia_personal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('presente', 'ausente', 'tardanza', 'permiso', name='estadoasistenciapersonal'), server_default='presente', nullable=False),
    sa.Column('entrada_en', sa.DateTime(), nullable=True),
    sa.Column('salida_en', sa.DateTime(), nullable=True),
    sa.Column('justificado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('registrado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asistencia_personal_entrada_en'), 'asistencia_personal', ['entrada_en'], unique=False)
    op.create_index(op.f('ix_asistencia_personal_estado'), 'asistencia_personal', ['estado'], unique=False)
    op.create_index(op.f('ix_asistencia_personal_fecha'), 'asistencia_personal', ['fecha'], unique=False)
    op.create_index(op.f('ix_asistencia_personal_justificado'), 'asistencia_personal', ['justificado'], unique=False)
    op.create_index(op.f('ix_asistencia_personal_salida_en'), 'asistencia_personal', ['salida_en'], unique=False)
    op.create_index(op.f('ix_asistencia_personal_sede_id'), 'asistencia_personal', ['sede_id'], unique=False)
    op.create_index(op.f('ix_asistencia_personal_usuario_id'), 'asistencia_personal', ['usuario_id'], unique=False)
    op.create_table('conversaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('directo', 'grupo', 'sistema', name='tipoconversacion'), server_default='directo', nullable=False),
    sa.Column('cerrado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversaciones_cerrado'), 'conversaciones', ['cerrado'], unique=False)
    op.create_index(op.f('ix_conversaciones_creado_por_id'), 'conversaciones', ['creado_por_id'], unique=False)
    op.create_index(op.f('ix_conversaciones_sede_id'), 'conversaciones', ['sede_id'], unique=False)
    op.create_index(op.f('ix_conversaciones_tipo'), 'conversaciones', ['tipo'], unique=False)
    op.create_index(op.f('ix_conversaciones_titulo'), 'conversaciones', ['titulo'], unique=False)
    op.create_table('costos_curso_extra',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('curso_extra_id', sa.Integer(), nullable=False),
    sa.Column('gestion', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['curso_extra_id'], ['cursos_extra.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_costos_curso_extra_curso_extra_id'), 'costos_curso_extra', ['curso_extra_id'], unique=False)
    op.create_index(op.f('ix_costos_curso_extra_gestion'), 'costos_curso_extra', ['gestion'], unique=False)
    op.create_table('ia_consultas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=False),
    sa.Column('tokens_consumidos', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ia_consultas_usuario_id'), 'ia_consultas', ['usuario_id'], unique=False)
    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=200), nullable=False),
    sa.Column('tipo_importacion', sa.String(length=80), nullable=False),
    sa.Column('archivo_url', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'procesando', 'completado', 'error', name='estadoimportacion'), server_default='pendiente', nullable=False),
    sa.Column('registros_procesados', sa.Integer(), nullable=False),
    sa.Column('registros_fallidos', sa.Integer(), nullable=False),
    sa.Column('log_errores', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_estado'), 'import_jobs', ['estado'], unique=False)
    op.create_index(op.f('ix_import_jobs_tipo_importacion'), 'import_jobs', ['tipo_importacion'], unique=False)
    op.create_index(op.f('ix_import_jobs_usuario_id'), 'import_jobs', ['usuario_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unidad_medida', sa.String(length=20), server_default='unidad', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_categoria_id'), 'items', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_items_codigo'), 'items', ['codigo'], unique=True)
    op.create_index(op.f('ix_items_nombre'), 'items', ['nombre'], unique=False)
    op.create_table('libro_caja',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ingreso', 'egreso', name='tipomovimiento'), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_libro_caja_fecha'), 'libro_caja', ['fecha'], unique=False)
    op.create_index(op.f('ix_libro_caja_registrado_por'), 'libro_caja', ['registrado_por'], unique=False)
    op.create_index(op.f('ix_libro_caja_sede_id'), 'libro_caja', ['sede_id'], unique=False)
    op.create_index(op.f('ix_libro_caja_tipo'), 'libro_caja', ['tipo'], unique=False)
    op.create_table('paralelos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('letra', sa.String(length=5), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grupo_id', 'letra', name='uq_grupo_letra')
    )
    op.create_index(op.f('ix_paralelos_activo'), 'paralelos', ['activo'], unique=False)
    op.create_index(op.f('ix_paralelos_grupo_id'), 'paralelos', ['grupo_id'], unique=False)
    op.create_index(op.f('ix_paralelos_letra'), 'paralelos', ['letra'], unique=False)
    op.create_table('permisos_personal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=80), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobado', 'rechazado', name='estadopermiso'), server_default='pendiente', nullable=False),
    sa.Column('aprobado_por', sa.Integer(), nullable=True),
    sa.Column('aprobado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permisos_personal_aprobado_en'), 'permisos_personal', ['aprobado_en'], unique=False)
    op.create_index(op.f('ix_permisos_personal_aprobado_por'), 'permisos_personal', ['aprobado_por'], unique=False)
    op.create_index(op.f('ix_permisos_personal_estado'), 'permisos_personal', ['estado'], unique=False)
    op.create_index(op.f('ix_permisos_personal_fecha_fin'), 'permisos_personal', ['fecha_fin'], unique=False)
    op.create_index(op.f('ix_permisos_personal_fecha_inicio'), 'permisos_personal', ['fecha_inicio'], unique=False)
    op.create_index(op.f('ix_permisos_personal_sede_id'), 'permisos_personal', ['sede_id'], unique=False)
    op.create_index(op.f('ix_permisos_personal_tipo'), 'permisos_personal', ['tipo'], unique=False)
    op.create_index(op.f('ix_permisos_personal_usuario_id'), 'permisos_personal', ['usuario_id'], unique=False)
    op.create_table('preferencias_usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tema', sa.String(length=20), server_default='claro', nullable=False),
    sa.Column('notificaciones_push', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('notificaciones_email', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preferencias_usuario_usuario_id'), 'preferencias_usuario', ['usuario_id'], unique=True)
    op.create_table('sesiones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_expira_en'), 'sesiones', ['expira_en'], unique=False)
    op.create_index(op.f('ix_sesiones_refresh_token'), 'sesiones', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_sesiones_usuario_id'), 'sesiones', ['usuario_id'], unique=False)
    op.create_table('usuarios_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('asignado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'rol_id', name='uq_usuario_rol')
    )
    op.create_index(op.f('ix_usuarios_roles_rol_id'), 'usuarios_roles', ['rol_id'], unique=False)
    op.create_index(op.f('ix_usuarios_roles_usuario_id'), 'usuarios_roles', ['usuario_id'], unique=False)
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paralelo_id', sa.Integer(), nullable=False),
    sa.Column('profesora_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_actividad', sa.Date(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paralelo_id'], ['paralelos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profesora_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actividades_fecha_actividad'), 'actividades', ['fecha_actividad'], unique=False)
    op.create_index(op.f('ix_actividades_paralelo_id'), 'actividades', ['paralelo_id'], unique=False)
    op.create_index(op.f('ix_actividades_profesora_id'), 'actividades', ['profesora_id'], unique=False)
    op.create_table('alertas_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('resuelta', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resuelta_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_stock_item_id'), 'alertas_stock', ['item_id'], unique=False)
    op.create_index(op.f('ix_alertas_stock_resuelta'), 'alertas_stock', ['resuelta'], unique=False)
    op.create_index(op.f('ix_alertas_stock_sede_id'), 'alertas_stock', ['sede_id'], unique=False)
    op.create_table('alertas_vencimiento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('notificada', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_vencimiento_fecha_vencimiento'), 'alertas_vencimiento', ['fecha_vencimiento'], unique=False)
    op.create_index(op.f('ix_alertas_vencimiento_item_id'), 'alertas_vencimiento', ['item_id'], unique=False)
    op.create_index(op.f('ix_alertas_vencimiento_notificada'), 'alertas_vencimiento', ['notificada'], unique=False)
    op.create_index(op.f('ix_alertas_vencimiento_sede_id'), 'alertas_vencimiento', ['sede_id'], unique=False)
    op.create_table('alumnos_paralelos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('paralelo_id', sa.Integer(), nullable=False),
    sa.Column('gestion', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('fecha_salida', sa.Date(), nullable=True),
    sa.Column('actual', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paralelo_id'], ['paralelos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alumno_id', 'paralelo_id', 'gestion', name='uq_alumno_paralelo_gestion')
    )
    op.create_index(op.f('ix_alumnos_paralelos_actual'), 'alumnos_paralelos', ['actual'], unique=False)
    op.create_index(op.f('ix_alumnos_paralelos_alumno_id'), 'alumnos_paralelos', ['alumno_id'], unique=False)
    op.create_index(op.f('ix_alumnos_paralelos_fecha_ingreso'), 'alumnos_paralelos', ['fecha_ingreso'], unique=False)
    op.create_index(op.f('ix_alumnos_paralelos_fecha_salida'), 'alumnos_paralelos', ['fecha_salida'], unique=False)
    op.create_index(op.f('ix_alumnos_paralelos_gestion'), 'alumnos_paralelos', ['gestion'], unique=False)
    op.create_index(op.f('ix_alumnos_paralelos_paralelo_id'), 'alumnos_paralelos', ['paralelo_id'], unique=False)
    op.create_table('asistencia_alumnos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('paralelo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('presente', 'ausente', 'tardanza', 'permiso', name='estadoasistenciaalumno'), server_default='presente', nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('registrado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paralelo_id'], ['paralelos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asistencia_alumnos_alumno_id'), 'asistencia_alumnos', ['alumno_id'], unique=False)
    op.create_index(op.f('ix_asistencia_alumnos_estado'), 'asistencia_alumnos', ['estado'], unique=False)
    op.create_index(op.f('ix_asistencia_alumnos_fecha'), 'asistencia_alumnos', ['fecha'], unique=False)
    op.create_index(op.f('ix_asistencia_alumnos_paralelo_id'), 'asistencia_alumnos', ['paralelo_id'], unique=False)
    op.create_index(op.f('ix_asistencia_alumnos_registrado_por'), 'asistencia_alumnos', ['registrado_por'], unique=False)
    op.create_table('auditoria_acciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('sede_id', sa.Integer(), nullable=True),
    sa.Column('entidad', sa.String(length=120), nullable=False),
    sa.Column('entidad_id', sa.String(length=64), nullable=True),
    sa.Column('accion', sa.String(length=30), nullable=False),
    sa.Column('datos_antes', sa.JSON(), nullable=True),
    sa.Column('datos_despues', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('sesion_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_acciones_accion'), 'auditoria_acciones', ['accion'], unique=False)
    op.create_index(op.f('ix_auditoria_acciones_creado_en'), 'auditoria_acciones', ['creado_en'], unique=False)
    op.create_index(op.f('ix_auditoria_acciones_entidad'), 'auditoria_acciones', ['entidad'], unique=False)
    op.create_index(op.f('ix_auditoria_acciones_entidad_id'), 'auditoria_acciones', ['entidad_id'], unique=False)
    op.create_index(op.f('ix_auditoria_acciones_ip'), 'auditoria_acciones', ['ip'], unique=False)
    op.create_index(op.f('ix_auditoria_acciones_sede_id'), 'auditoria_acciones', ['sede_id'], unique=False)
    op.create_index(op.f('ix_auditoria_acciones_sesion_id'), 'auditoria_acciones', ['sesion_id'], unique=False)
    op.create_index(op.f('ix_auditoria_acciones_usuario_id'), 'auditoria_acciones', ['usuario_id'], unique=False)
    op.create_table('codigos_acceso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('gestion', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('usuario_destino_id', sa.Integer(), nullable=True),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('max_cuentas', sa.Integer(), nullable=False),
    sa.Column('cuentas_creadas', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=8), nullable=False),
    sa.Column('expira_en', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'enviado', 'consumido', 'expirado', 'revocado', name='estadocodigo'), server_default='pendiente', nullable=False),
    sa.Column('whatsapp_numero', sa.String(length=20), nullable=False),
    sa.Column('whatsapp_message_id', sa.String(length=100), nullable=True),
    sa.Column('enviado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('enviado_en', sa.DateTime(), nullable=True),
    sa.Column('entregado_a', sa.String(length=140), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_destino_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_codigo_acceso')
    )
    op.create_index(op.f('ix_codigos_acceso_alumno_id'), 'codigos_acceso', ['alumno_id'], unique=False)
    op.create_index(op.f('ix_codigos_acceso_codigo'), 'codigos_acceso', ['codigo'], unique=True)
    op.create_index(op.f('ix_codigos_acceso_creado_en'), 'codigos_acceso', ['creado_en'], unique=False)
    op.create_index(op.f('ix_codigos_acceso_creado_por'), 'codigos_acceso', ['creado_por'], unique=False)
    op.create_index(op.f('ix_codigos_acceso_enviado'), 'codigos_acceso', ['enviado'], unique=False)
    op.create_index(op.f('ix_codigos_acceso_enviado_en'), 'codigos_acceso', ['enviado_en'], unique=False)
    op.create_index(op.f('ix_codigos_acceso_estado'), 'codigos_acceso', ['estado'], unique=False)
    op.create_index(op.f('ix_codigos_acceso_expira_en'), 'codigos_acceso', ['expira_en'], unique=False)
    op.create_index(op.f('ix_codigos_acceso_gestion'), 'codigos_acceso', ['gestion'], unique=False)
    op.create_index(op.f('ix_codigos_acceso_rol_id'), 'codigos_acceso', ['rol_id'], unique=False)
    op.create_index(op.f('ix_codigos_acceso_sede_id'), 'codigos_acceso', ['sede_id'], unique=False)
    op.create_index(op.f('ix_codigos_acceso_usuario_destino_id'), 'codigos_acceso', ['usuario_destino_id'], unique=False)
    op.create_index(op.f('ix_codigos_acceso_whatsapp_message_id'), 'codigos_acceso', ['whatsapp_message_id'], unique=False)
    op.create_index(op.f('ix_codigos_acceso_whatsapp_numero'), 'codigos_acceso', ['whatsapp_numero'], unique=False)
    op.create_table('consentimientos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('firmado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('firma_url', sa.String(length=255), nullable=True),
    sa.Column('firmado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tutor_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consentimientos_alumno_id'), 'consentimientos', ['alumno_id'], unique=False)
    op.create_index(op.f('ix_consentimientos_firmado'), 'consentimientos', ['firmado'], unique=False)
    op.create_index(op.f('ix_consentimientos_firmado_en'), 'consentimientos', ['firmado_en'], unique=False)
    op.create_index(op.f('ix_consentimientos_tipo'), 'consentimientos', ['tipo'], unique=False)
    op.create_index(op.f('ix_consentimientos_tutor_id'), 'consentimientos', ['tutor_id'], unique=False)
    op.create_table('estado_cuenta_nino',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('saldo_anterior', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_cargos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_pagos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('saldo_actual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pdf_url', sa.String(length=255), nullable=True),
    sa.Column('generado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estado_cuenta_nino_alumno_id'), 'estado_cuenta_nino', ['alumno_id'], unique=False)
    op.create_index(op.f('ix_estado_cuenta_nino_anio'), 'estado_cuenta_nino', ['anio'], unique=False)
    op.create_index(op.f('ix_estado_cuenta_nino_mes'), 'estado_cuenta_nino', ['mes'], unique=False)
    op.create_table('formularios_inscripcion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('gestion', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('borrador', 'enviado', 'aprobado', 'rechazado', name='estadoformulario'), server_default='borrador', nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formularios_inscripcion_alumno_id'), 'formularios_inscripcion', ['alumno_id'], unique=False)
    op.create_index(op.f('ix_formularios_inscripcion_estado'), 'formularios_inscripcion', ['estado'], unique=False)
    op.create_index(op.f('ix_formularios_inscripcion_gestion'), 'formularios_inscripcion', ['gestion'], unique=False)
    op.create_index(op.f('ix_formularios_inscripcion_sede_id'), 'formularios_inscripcion', ['sede_id'], unique=False)
    op.create_table('horarios_paralelos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paralelo_id', sa.Integer(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=False),
    sa.Column('desde', sa.Date(), nullable=False),
    sa.Column('hasta', sa.Date(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['horario_id'], ['horarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['paralelo_id'], ['paralelos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paralelo_id', 'horario_id', 'desde', name='uq_paralelo_horario_desde')
    )
    op.create_index(op.f('ix_horarios_paralelos_desde'), 'horarios_paralelos', ['desde'], unique=False)
    op.create_index(op.f('ix_horarios_paralelos_hasta'), 'horarios_paralelos', ['hasta'], unique=False)
    op.create_index(op.f('ix_horarios_paralelos_horario_id'), 'horarios_paralelos', ['horario_id'], unique=False)
    op.create_index(op.f('ix_horarios_paralelos_paralelo_id'), 'horarios_paralelos', ['paralelo_id'], unique=False)
    op.create_table('inscripciones_curso_extra',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('curso_extra_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inscripcion', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'completado', 'retirado', name='estadoinscripcioncursoextra'), server_default='activo', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['curso_extra_id'], ['cursos_extra.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inscripciones_curso_extra_alumno_id'), 'inscripciones_curso_extra', ['alumno_id'], unique=False)
    op.create_index(op.f('ix_inscripciones_curso_extra_curso_extra_id'), 'inscripciones_curso_extra', ['curso_extra_id'], unique=False)
    op.create_index(op.f('ix_inscripciones_curso_extra_estado'), 'inscripciones_curso_extra', ['estado'], unique=False)
    op.create_index(op.f('ix_inscripciones_curso_extra_fecha_inscripcion'), 'inscripciones_curso_extra', ['fecha_inscripcion'], unique=False)
    op.create_table('items_atributos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('nombre_atributo', sa.String(length=60), nullable=False),
    sa.Column('valor_atributo', sa.String(length=120), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_atributos_item_id'), 'items_atributos', ['item_id'], unique=False)
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversacion_id', sa.Integer(), nullable=False),
    sa.Column('remitente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('texto', 'sistema', name='tipomensaje'), server_default='texto', nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('reply_a_id', sa.Integer(), nullable=True),
    sa.Column('enviado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['remitente_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reply_a_id'], ['mensajes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_conversacion_id'), 'mensajes', ['conversacion_id'], unique=False)
    op.create_index(op.f('ix_mensajes_enviado_en'), 'mensajes', ['enviado_en'], unique=False)
    op.create_index(op.f('ix_mensajes_remitente_id'), 'mensajes', ['remitente_id'], unique=False)
    op.create_index(op.f('ix_mensajes_reply_a_id'), 'mensajes', ['reply_a_id'], unique=False)
    op.create_index(op.f('ix_mensajes_tipo'), 'mensajes', ['tipo'], unique=False)
    op.create_table('movimientos_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'salida', 'transferencia', 'ajuste', name='tipomovimiento'), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_movimiento', sa.Date(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_stock_fecha_movimiento'), 'movimientos_stock', ['fecha_movimiento'], unique=False)
    op.create_index(op.f('ix_movimientos_stock_item_id'), 'movimientos_stock', ['item_id'], unique=False)
    op.create_index(op.f('ix_movimientos_stock_sede_id'), 'movimientos_stock', ['sede_id'], unique=False)
    op.create_index(op.f('ix_movimientos_stock_tipo'), 'movimientos_stock', ['tipo'], unique=False)
    op.create_index(op.f('ix_movimientos_stock_usuario_id'), 'movimientos_stock', ['usuario_id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('categoria_pago_id', sa.Integer(), nullable=False),
    sa.Column('monto_pagado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=False),
    sa.Column('numero_comprobante', sa.String(length=80), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['categoria_pago_id'], ['categorias_pago.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_alumno_id'), 'pagos', ['alumno_id'], unique=False)
    op.create_index(op.f('ix_pagos_categoria_pago_id'), 'pagos', ['categoria_pago_id'], unique=False)
    op.create_index(op.f('ix_pagos_fecha_pago'), 'pagos', ['fecha_pago'], unique=False)
    op.create_index(op.f('ix_pagos_metodo_pago'), 'pagos', ['metodo_pago'], unique=False)
    op.create_index(op.f('ix_pagos_numero_comprobante'), 'pagos', ['numero_comprobante'], unique=False)
    op.create_index(op.f('ix_pagos_registrado_por'), 'pagos', ['registrado_por'], unique=False)
    op.create_table('paralelos_profesoras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paralelo_id', sa.Integer(), nullable=False),
    sa.Column('profesora_id', sa.Integer(), nullable=False),
    sa.Column('gestion', sa.Integer(), nullable=False),
    sa.Column('desde', sa.Date(), nullable=True),
    sa.Column('hasta', sa.Date(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paralelo_id'], ['paralelos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profesora_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paralelo_id', 'profesora_id', 'gestion', name='uq_paralelo_profesora_gestion')
    )
    op.create_index(op.f('ix_paralelos_profesoras_desde'), 'paralelos_profesoras', ['desde'], unique=False)
    op.create_index(op.f('ix_paralelos_profesoras_gestion'), 'paralelos_profesoras', ['gestion'], unique=False)
    op.create_index(op.f('ix_paralelos_profesoras_hasta'), 'paralelos_profesoras', ['hasta'], unique=False)
    op.create_index(op.f('ix_paralelos_profesoras_paralelo_id'), 'paralelos_profesoras', ['paralelo_id'], unique=False)
    op.create_index(op.f('ix_paralelos_profesoras_profesora_id'), 'paralelos_profesoras', ['profesora_id'], unique=False)
    op.create_table('planes_pago',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('gestion', sa.Integer(), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planes_pago_alumno_id'), 'planes_pago', ['alumno_id'], unique=False)
    op.create_index(op.f('ix_planes_pago_gestion'), 'planes_pago', ['gestion'], unique=False)
    op.create_table('prestamos_uniformes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('fecha_prestamo', sa.Date(), nullable=False),
    sa.Column('fecha_devolucion', sa.Date(), nullable=True),
    sa.Column('devuelto', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prestamos_uniformes_alumno_id'), 'prestamos_uniformes', ['alumno_id'], unique=False)
    op.create_index(op.f('ix_prestamos_uniformes_fecha_devolucion'), 'prestamos_uniformes', ['fecha_devolucion'], unique=False)
    op.create_index(op.f('ix_prestamos_uniformes_fecha_prestamo'), 'prestamos_uniformes', ['fecha_prestamo'], unique=False)
    op.create_index(op.f('ix_prestamos_uniformes_item_id'), 'prestamos_uniformes', ['item_id'], unique=False)
    op.create_table('reportes_diarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paralelo_id', sa.Integer(), nullable=False),
    sa.Column('profesora_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paralelo_id'], ['paralelos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profesora_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportes_diarios_fecha'), 'reportes_diarios', ['fecha'], unique=False)
    op.create_index(op.f('ix_reportes_diarios_paralelo_id'), 'reportes_diarios', ['paralelo_id'], unique=False)
    op.create_index(op.f('ix_reportes_diarios_profesora_id'), 'reportes_diarios', ['profesora_id'], unique=False)
    op.create_table('stock_sede',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_disponible', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'sede_id', name='uq_item_sede')
    )
    op.create_index(op.f('ix_stock_sede_item_id'), 'stock_sede', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_sede_sede_id'), 'stock_sede', ['sede_id'], unique=False)
    op.create_table('actividad_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('imagen', 'video', 'audio', 'documento', name='tipomedia'), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actividad_media_actividad_id'), 'actividad_media', ['actividad_id'], unique=False)
    op.create_table('balance_curso_extra',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inscripcion_curso_extra_id', sa.Integer(), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_pagado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'pagado', name='estadobalance'), server_default='pendiente', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inscripcion_curso_extra_id'], ['inscripciones_curso_extra.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_curso_extra_estado'), 'balance_curso_extra', ['estado'], unique=False)
    op.create_index(op.f('ix_balance_curso_extra_fecha_vencimiento'), 'balance_curso_extra', ['fecha_vencimiento'], unique=False)
    op.create_index(op.f('ix_balance_curso_extra_inscripcion_curso_extra_id'), 'balance_curso_extra', ['inscripcion_curso_extra_id'], unique=False)
    op.create_table('codigos_acceso_usos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('consumido_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['codigo_id'], ['codigos_acceso.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_id', 'usuario_id', name='uq_codigo_usuario')
    )
    op.create_index(op.f('ix_codigos_acceso_usos_codigo_id'), 'codigos_acceso_usos', ['codigo_id'], unique=False)
    op.create_index(op.f('ix_codigos_acceso_usos_consumido_en'), 'codigos_acceso_usos', ['consumido_en'], unique=False)
    op.create_index(op.f('ix_codigos_acceso_usos_rol_id'), 'codigos_acceso_usos', ['rol_id'], unique=False)
    op.create_index(op.f('ix_codigos_acceso_usos_usuario_id'), 'codigos_acceso_usos', ['usuario_id'], unique=False)
    op.create_table('comprobantes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=120), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comprobantes_pago_id'), 'comprobantes', ['pago_id'], unique=False)
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.Column('codigo_contrato', sa.String(length=30), nullable=False),
    sa.Column('pdf_url', sa.String(length=255), nullable=True),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['formulario_id'], ['formularios_inscripcion.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_codigo_contrato'), 'contratos', ['codigo_contrato'], unique=True)
    op.create_index(op.f('ix_contratos_fecha_emision'), 'contratos', ['fecha_emision'], unique=False)
    op.create_index(op.f('ix_contratos_formulario_id'), 'contratos', ['formulario_id'], unique=False)
    op.create_table('documentos_inscripcion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=120), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['formulario_id'], ['formularios_inscripcion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_inscripcion_formulario_id'), 'documentos_inscripcion', ['formulario_id'], unique=False)
    op.create_index(op.f('ix_documentos_inscripcion_tipo_documento'), 'documentos_inscripcion', ['tipo_documento'], unique=False)
    op.create_table('firmas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.Column('firmante', sa.String(length=120), nullable=False),
    sa.Column('firma_url', sa.String(length=255), nullable=False),
    sa.Column('firmado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['formulario_id'], ['formularios_inscripcion.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmas_formulario_id'), 'firmas', ['formulario_id'], unique=False)
    op.create_table('formularios_respuestas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.Column('campo', sa.String(length=80), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['formulario_id'], ['formularios_inscripcion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formularios_respuestas_formulario_id'), 'formularios_respuestas', ['formulario_id'], unique=False)
    op.create_table('mensajes_adjuntos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mensaje_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('imagen', 'video', 'audio', 'documento', name='tipoadjunto'), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=160), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mensaje_id'], ['mensajes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_adjuntos_mensaje_id'), 'mensajes_adjuntos', ['mensaje_id'], unique=False)
    op.create_index(op.f('ix_mensajes_adjuntos_tipo'), 'mensajes_adjuntos', ['tipo'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=140), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=True),
    sa.Column('canal', sa.Enum('app', 'email', 'sms', name='canalnotificacion'), server_default='app', nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'enviada', 'fallida', name='estadonotificacion'), server_default='pendiente', nullable=False),
    sa.Column('relacionado_mensaje_id', sa.Integer(), nullable=True),
    sa.Column('enviado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('enviado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destinatario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relacionado_mensaje_id'], ['mensajes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_canal'), 'notificaciones', ['canal'], unique=False)
    op.create_index(op.f('ix_notificaciones_destinatario_id'), 'notificaciones', ['destinatario_id'], unique=False)
    op.create_index(op.f('ix_notificaciones_enviado'), 'notificaciones', ['enviado'], unique=False)
    op.create_index(op.f('ix_notificaciones_enviado_en'), 'notificaciones', ['enviado_en'], unique=False)
    op.create_index(op.f('ix_notificaciones_estado'), 'notificaciones', ['estado'], unique=False)
    op.create_index(op.f('ix_notificaciones_relacionado_mensaje_id'), 'notificaciones', ['relacionado_mensaje_id'], unique=False)
    op.create_table('planes_cuotas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_pago_id', sa.Integer(), nullable=False),
    sa.Column('numero_cuota', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'pagado', 'vencido', name='estadocuota'), server_default='pendiente', nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_pago_id'], ['planes_pago.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planes_cuotas_estado'), 'planes_cuotas', ['estado'], unique=False)
    op.create_index(op.f('ix_planes_cuotas_fecha_vencimiento'), 'planes_cuotas', ['fecha_vencimiento'], unique=False)
    op.create_index(op.f('ix_planes_cuotas_plan_pago_id'), 'planes_cuotas', ['plan_pago_id'], unique=False)
    op.create_table('reporte_lecturas_tutores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reporte_diario_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('leido_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporte_diario_id'], ['reportes_diarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tutor_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporte_diario_id', 'tutor_id', name='uq_reporte_tutor')
    )
    op.create_index(op.f('ix_reporte_lecturas_tutores_reporte_diario_id'), 'reporte_lecturas_tutores', ['reporte_diario_id'], unique=False)
    op.create_index(op.f('ix_reporte_lecturas_tutores_tutor_id'), 'reporte_lecturas_tutores', ['tutor_id'], unique=False)
    op.create_table('conciliaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('comprobante_id', sa.Integer(), nullable=True),
    sa.Column('monto_conciliado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_conciliacion', sa.Date(), nullable=False),
    sa.Column('conciliado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('conciliado_por', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['conciliado_por'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conciliaciones_comprobante_id'), 'conciliaciones', ['comprobante_id'], unique=False)
    op.create_index(op.f('ix_conciliaciones_conciliado'), 'conciliaciones', ['conciliado'], unique=False)
    op.create_index(op.f('ix_conciliaciones_conciliado_por'), 'conciliaciones', ['conciliado_por'], unique=False)
    op.create_index(op.f('ix_conciliaciones_fecha_conciliacion'), 'conciliaciones', ['fecha_conciliacion'], unique=False)
    op.create_index(op.f('ix_conciliaciones_pago_id'), 'conciliaciones', ['pago_id'], unique=False)
    op.create_table('notificacion_vistas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notificacion_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('visto_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notificacion_id'], ['notificaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notificacion_id', 'usuario_id', name='uq_notificacion_usuario')
    )
    op.create_index(op.f('ix_notificacion_vistas_notificacion_id'), 'notificacion_vistas', ['notificacion_id'], unique=False)
    op.create_index(op.f('ix_notificacion_vistas_usuario_id'), 'notificacion_vistas', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_notificacion_vistas_visto_en'), 'notificacion_vistas', ['visto_en'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notificacion_vistas_visto_en'), table_name='notificacion_vistas')
    op.drop_index(op.f('ix_notificacion_vistas_usuario_id'), table_name='notificacion_vistas')
    op.drop_index(op.f('ix_notificacion_vistas_notificacion_id'), table_name='notificacion_vistas')
    op.drop_table('notificacion_vistas')
    op.drop_index(op.f('ix_conciliaciones_pago_id'), table_name='conciliaciones')
    op.drop_index(op.f('ix_conciliaciones_fecha_conciliacion'), table_name='conciliaciones')
    op.drop_index(op.f('ix_conciliaciones_conciliado_por'), table_name='conciliaciones')
    op.drop_index(op.f('ix_conciliaciones_conciliado'), table_name='conciliaciones')
    op.drop_index(op.f('ix_conciliaciones_comprobante_id'), table_name='conciliaciones')
    op.drop_table('conciliaciones')
    op.drop_index(op.f('ix_reporte_lecturas_tutores_tutor_id'), table_name='reporte_lecturas_tutores')
    op.drop_index(op.f('ix_reporte_lecturas_tutores_reporte_diario_id'), table_name='reporte_lecturas_tutores')
    op.drop_table('reporte_lecturas_tutores')
    op.drop_index(op.f('ix_planes_cuotas_plan_pago_id'), table_name='planes_cuotas')
    op.drop_index(op.f('ix_planes_cuotas_fecha_vencimiento'), table_name='planes_cuotas')
    op.drop_index(op.f('ix_planes_cuotas_estado'), table_name='planes_cuotas')
    op.drop_table('planes_cuotas')
    op.drop_index(op.f('ix_notificaciones_relacionado_mensaje_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_estado'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_enviado_en'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_enviado'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_destinatario_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_canal'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_mensajes_adjuntos_tipo'), table_name='mensajes_adjuntos')
    op.drop_index(op.f('ix_mensajes_adjuntos_mensaje_id'), table_name='mensajes_adjuntos')
    op.drop_table('mensajes_adjuntos')
    op.drop_index(op.f('ix_formularios_respuestas_formulario_id'), table_name='formularios_respuestas')
    op.drop_table('formularios_respuestas')
    op.drop_index(op.f('ix_firmas_formulario_id'), table_name='firmas')
    op.drop_table('firmas')
    op.drop_index(op.f('ix_documentos_inscripcion_tipo_documento'), table_name='documentos_inscripcion')
    op.drop_index(op.f('ix_documentos_inscripcion_formulario_id'), table_name='documentos_inscripcion')
    op.drop_table('documentos_inscripcion')
    op.drop_index(op.f('ix_contratos_formulario_id'), table_name='contratos')
    op.drop_index(op.f('ix_contratos_fecha_emision'), table_name='contratos')
    op.drop_index(op.f('ix_contratos_codigo_contrato'), table_name='contratos')
    op.drop_table('contratos')
    op.drop_index(op.f('ix_comprobantes_pago_id'), table_name='comprobantes')
    op.drop_table('comprobantes')
    op.drop_index(op.f('ix_codigos_acceso_usos_usuario_id'), table_name='codigos_acceso_usos')
    op.drop_index(op.f('ix_codigos_acceso_usos_rol_id'), table_name='codigos_acceso_usos')
    op.drop_index(op.f('ix_codigos_acceso_usos_consumido_en'), table_name='codigos_acceso_usos')
    op.drop_index(op.f('ix_codigos_acceso_usos_codigo_id'), table_name='codigos_acceso_usos')
    op.drop_table('codigos_acceso_usos')
    op.drop_index(op.f('ix_balance_curso_extra_inscripcion_curso_extra_id'), table_name='balance_curso_extra')
    op.drop_index(op.f('ix_balance_curso_extra_fecha_vencimiento'), table_name='balance_curso_extra')
    op.drop_index(op.f('ix_balance_curso_extra_estado'), table_name='balance_curso_extra')
    op.drop_table('balance_curso_extra')
    op.drop_index(op.f('ix_actividad_media_actividad_id'), table_name='actividad_media')
    op.drop_table('actividad_media')
    op.drop_index(op.f('ix_stock_sede_sede_id'), table_name='stock_sede')
    op.drop_index(op.f('ix_stock_sede_item_id'), table_name='stock_sede')
    op.drop_table('stock_sede')
    op.drop_index(op.f('ix_reportes_diarios_profesora_id'), table_name='reportes_diarios')
    op.drop_index(op.f('ix_reportes_diarios_paralelo_id'), table_name='reportes_diarios')
    op.drop_index(op.f('ix_reportes_diarios_fecha'), table_name='reportes_diarios')
    op.drop_table('reportes_diarios')
    op.drop_index(op.f('ix_prestamos_uniformes_item_id'), table_name='prestamos_uniformes')
    op.drop_index(op.f('ix_prestamos_uniformes_fecha_prestamo'), table_name='prestamos_uniformes')
    op.drop_index(op.f('ix_prestamos_uniformes_fecha_devolucion'), table_name='prestamos_uniformes')
    op.drop_index(op.f('ix_prestamos_uniformes_alumno_id'), table_name='prestamos_uniformes')
    op.drop_table('prestamos_uniformes')
    op.drop_index(op.f('ix_planes_pago_gestion'), table_name='planes_pago')
    op.drop_index(op.f('ix_planes_pago_alumno_id'), table_name='planes_pago')
    op.drop_table('planes_pago')
    op.drop_index(op.f('ix_paralelos_profesoras_profesora_id'), table_name='paralelos_profesoras')
    op.drop_index(op.f('ix_paralelos_profesoras_paralelo_id'), table_name='paralelos_profesoras')
    op.drop_index(op.f('ix_paralelos_profesoras_hasta'), table_name='paralelos_profesoras')
    op.drop_index(op.f('ix_paralelos_profesoras_gestion'), table_name='paralelos_profesoras')
    op.drop_index(op.f('ix_paralelos_profesoras_desde'), table_name='paralelos_profesoras')
    op.drop_table('paralelos_profesoras')
    op.drop_index(op.f('ix_pagos_registrado_por'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_numero_comprobante'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_metodo_pago'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_fecha_pago'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_categoria_pago_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_alumno_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_movimientos_stock_usuario_id'), table_name='movimientos_stock')
    op.drop_index(op.f('ix_movimientos_stock_tipo'), table_name='movimientos_stock')
    op.drop_index(op.f('ix_movimientos_stock_sede_id'), table_name='movimientos_stock')
    op.drop_index(op.f('ix_movimientos_stock_item_id'), table_name='movimientos_stock')
    op.drop_index(op.f('ix_movimientos_stock_fecha_movimiento'), table_name='movimientos_stock')
    op.drop_table('movimientos_stock')
    op.drop_index(op.f('ix_mensajes_tipo'), table_name='mensajes')
    op.drop_index(op.f('ix_mensajes_reply_a_id'), table_name='mensajes')
    op.drop_index(op.f('ix_mensajes_remitente_id'), table_name='mensajes')
    op.drop_index(op.f('ix_mensajes_enviado_en'), table_name='mensajes')
    op.drop_index(op.f('ix_mensajes_conversacion_id'), table_name='mensajes')
    op.drop_table('mensajes')
    op.drop_index(op.f('ix_items_atributos_item_id'), table_name='items_atributos')
    op.drop_table('items_atributos')
    op.drop_index(op.f('ix_inscripciones_curso_extra_fecha_inscripcion'), table_name='inscripciones_curso_extra')
    op.drop_index(op.f('ix_inscripciones_curso_extra_estado'), table_name='inscripciones_curso_extra')
    op.drop_index(op.f('ix_inscripciones_curso_extra_curso_extra_id'), table_name='inscripciones_curso_extra')
    op.drop_index(op.f('ix_inscripciones_curso_extra_alumno_id'), table_name='inscripciones_curso_extra')
    op.drop_table('inscripciones_curso_extra')
    op.drop_index(op.f('ix_horarios_paralelos_paralelo_id'), table_name='horarios_paralelos')
    op.drop_index(op.f('ix_horarios_paralelos_horario_id'), table_name='horarios_paralelos')
    op.drop_index(op.f('ix_horarios_paralelos_hasta'), table_name='horarios_paralelos')
    op.drop_index(op.f('ix_horarios_paralelos_desde'), table_name='horarios_paralelos')
    op.drop_table('horarios_paralelos')
    op.drop_index(op.f('ix_formularios_inscripcion_sede_id'), table_name='formularios_inscripcion')
    op.drop_index(op.f('ix_formularios_inscripcion_gestion'), table_name='formularios_inscripcion')
    op.drop_index(op.f('ix_formularios_inscripcion_estado'), table_name='formularios_inscripcion')
    op.drop_index(op.f('ix_formularios_inscripcion_alumno_id'), table_name='formularios_inscripcion')
    op.drop_table('formularios_inscripcion')
    op.drop_index(op.f('ix_estado_cuenta_nino_mes'), table_name='estado_cuenta_nino')
    op.drop_index(op.f('ix_estado_cuenta_nino_anio'), table_name='estado_cuenta_nino')
    op.drop_index(op.f('ix_estado_cuenta_nino_alumno_id'), table_name='estado_cuenta_nino')
    op.drop_table('estado_cuenta_nino')
    op.drop_index(op.f('ix_consentimientos_tutor_id'), table_name='consentimientos')
    op.drop_index(op.f('ix_consentimientos_tipo'), table_name='consentimientos')
    op.drop_index(op.f('ix_consentimientos_firmado_en'), table_name='consentimientos')
    op.drop_index(op.f('ix_consentimientos_firmado'), table_name='consentimientos')
    op.drop_index(op.f('ix_consentimientos_alumno_id'), table_name='consentimientos')
    op.drop_table('consentimientos')
    op.drop_index(op.f('ix_codigos_acceso_whatsapp_numero'), table_name='codigos_acceso')
    op.drop_index(op.f('ix_codigos_acceso_whatsapp_message_id'), table_name='codigos_acceso')
    op.drop_index(op.f('ix_codigos_acceso_usuario_destino_id'), table_name='codigos_acceso')
    op.drop_index(op.f('ix_codigos_acceso_sede_id'), table_name='codigos_acceso')
    op.drop_index(op.f('ix_codigos_acceso_rol_id'), table_name='codigos_acceso')
    op.drop_index(op.f('ix_codigos_acceso_gestion'), table_name='codigos_acceso')
    op.drop_index(op.f('ix_codigos_acceso_expira_en'), table_name='codigos_acceso')
    op.drop_index(op.f('ix_codigos_acceso_estado'), table_name='codigos_acceso')
    op.drop_index(op.f('ix_codigos_acceso_enviado_en'), table_name='codigos_acceso')
    op.drop_index(op.f('ix_codigos_acceso_enviado'), table_name='codigos_acceso')
    op.drop_index(op.f('ix_codigos_acceso_creado_por'), table_name='codigos_acceso')
    op.drop_index(op.f('ix_codigos_acceso_creado_en'), table_name='codigos_acceso')
    op.drop_index(op.f('ix_codigos_acceso_codigo'), table_name='codigos_acceso')
    op.drop_index(op.f('ix_codigos_acceso_alumno_id'), table_name='codigos_acceso')
    op.drop_table('codigos_acceso')
    op.drop_index(op.f('ix_auditoria_acciones_usuario_id'), table_name='auditoria_acciones')
    op.drop_index(op.f('ix_auditoria_acciones_sesion_id'), table_name='auditoria_acciones')
    op.drop_index(op.f('ix_auditoria_acciones_sede_id'), table_name='auditoria_acciones')
    op.drop_index(op.f('ix_auditoria_acciones_ip'), table_name='auditoria_acciones')
    op.drop_index(op.f('ix_auditoria_acciones_entidad_id'), table_name='auditoria_acciones')
    op.drop_index(op.f('ix_auditoria_acciones_entidad'), table_name='auditoria_acciones')
    op.drop_index(op.f('ix_auditoria_acciones_creado_en'), table_name='auditoria_acciones')
    op.drop_index(op.f('ix_auditoria_acciones_accion'), table_name='auditoria_acciones')
    op.drop_table('auditoria_acciones')
    op.drop_index(op.f('ix_asistencia_alumnos_registrado_por'), table_name='asistencia_alumnos')
    op.drop_index(op.f('ix_asistencia_alumnos_paralelo_id'), table_name='asistencia_alumnos')
    op.drop_index(op.f('ix_asistencia_alumnos_fecha'), table_name='asistencia_alumnos')
    op.drop_index(op.f('ix_asistencia_alumnos_estado'), table_name='asistencia_alumnos')
    op.drop_index(op.f('ix_asistencia_alumnos_alumno_id'), table_name='asistencia_alumnos')
    op.drop_table('asistencia_alumnos')
    op.drop_index(op.f('ix_alumnos_paralelos_paralelo_id'), table_name='alumnos_paralelos')
    op.drop_index(op.f('ix_alumnos_paralelos_gestion'), table_name='alumnos_paralelos')
    op.drop_index(op.f('ix_alumnos_paralelos_fecha_salida'), table_name='alumnos_paralelos')
    op.drop_index(op.f('ix_alumnos_paralelos_fecha_ingreso'), table_name='alumnos_paralelos')
    op.drop_index(op.f('ix_alumnos_paralelos_alumno_id'), table_name='alumnos_paralelos')
    op.drop_index(op.f('ix_alumnos_paralelos_actual'), table_name='alumnos_paralelos')
    op.drop_table('alumnos_paralelos')
    op.drop_index(op.f('ix_alertas_vencimiento_sede_id'), table_name='alertas_vencimiento')
    op.drop_index(op.f('ix_alertas_vencimiento_notificada'), table_name='alertas_vencimiento')
    op.drop_index(op.f('ix_alertas_vencimiento_item_id'), table_name='alertas_vencimiento')
    op.drop_index(op.f('ix_alertas_vencimiento_fecha_vencimiento'), table_name='alertas_vencimiento')
    op.drop_table('alertas_vencimiento')
    op.drop_index(op.f('ix_alertas_stock_sede_id'), table_name='alertas_stock')
    op.drop_index(op.f('ix_alertas_stock_resuelta'), table_name='alertas_stock')
    op.drop_index(op.f('ix_alertas_stock_item_id'), table_name='alertas_stock')
    op.drop_table('alertas_stock')
    op.drop_index(op.f('ix_actividades_profesora_id'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_paralelo_id'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_fecha_actividad'), table_name='actividades')
    op.drop_table('actividades')
    op.drop_index(op.f('ix_usuarios_roles_usuario_id'), table_name='usuarios_roles')
    op.drop_index(op.f('ix_usuarios_roles_rol_id'), table_name='usuarios_roles')
    op.drop_table('usuarios_roles')
    op.drop_index(op.f('ix_sesiones_usuario_id'), table_name='sesiones')
    op.drop_index(op.f('ix_sesiones_refresh_token'), table_name='sesiones')
    op.drop_index(op.f('ix_sesiones_expira_en'), table_name='sesiones')
    op.drop_table('sesiones')
    op.drop_index(op.f('ix_preferencias_usuario_usuario_id'), table_name='preferencias_usuario')
    op.drop_table('preferencias_usuario')
    op.drop_index(op.f('ix_permisos_personal_usuario_id'), table_name='permisos_personal')
    op.drop_index(op.f('ix_permisos_personal_tipo'), table_name='permisos_personal')
    op.drop_index(op.f('ix_permisos_personal_sede_id'), table_name='permisos_personal')
    op.drop_index(op.f('ix_permisos_personal_fecha_inicio'), table_name='permisos_personal')
    op.drop_index(op.f('ix_permisos_personal_fecha_fin'), table_name='permisos_personal')
    op.drop_index(op.f('ix_permisos_personal_estado'), table_name='permisos_personal')
    op.drop_index(op.f('ix_permisos_personal_aprobado_por'), table_name='permisos_personal')
    op.drop_index(op.f('ix_permisos_personal_aprobado_en'), table_name='permisos_personal')
    op.drop_table('permisos_personal')
    op.drop_index(op.f('ix_paralelos_letra'), table_name='paralelos')
    op.drop_index(op.f('ix_paralelos_grupo_id'), table_name='paralelos')
    op.drop_index(op.f('ix_paralelos_activo'), table_name='paralelos')
    op.drop_table('paralelos')
    op.drop_index(op.f('ix_libro_caja_tipo'), table_name='libro_caja')
    op.drop_index(op.f('ix_libro_caja_sede_id'), table_name='libro_caja')
    op.drop_index(op.f('ix_libro_caja_registrado_por'), table_name='libro_caja')
    op.drop_index(op.f('ix_libro_caja_fecha'), table_name='libro_caja')
    op.drop_table('libro_caja')
    op.drop_index(op.f('ix_items_nombre'), table_name='items')
    op.drop_index(op.f('ix_items_codigo'), table_name='items')
    op.drop_index(op.f('ix_items_categoria_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_import_jobs_usuario_id'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_tipo_importacion'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_estado'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_ia_consultas_usuario_id'), table_name='ia_consultas')
    op.drop_table('ia_consultas')
    op.drop_index(op.f('ix_costos_curso_extra_gestion'), table_name='costos_curso_extra')
    op.drop_index(op.f('ix_costos_curso_extra_curso_extra_id'), table_name='costos_curso_extra')
    op.drop_table('costos_curso_extra')
    op.drop_index(op.f('ix_conversaciones_titulo'), table_name='conversaciones')
    op.drop_index(op.f('ix_conversaciones_tipo'), table_name='conversaciones')
    op.drop_index(op.f('ix_conversaciones_sede_id'), table_name='conversaciones')
    op.drop_index(op.f('ix_conversaciones_creado_por_id'), table_name='conversaciones')
    op.drop_index(op.f('ix_conversaciones_cerrado'), table_name='conversaciones')
    op.drop_table('conversaciones')
    op.drop_index(op.f('ix_asistencia_personal_usuario_id'), table_name='asistencia_personal')
    op.drop_index(op.f('ix_asistencia_personal_sede_id'), table_name='asistencia_personal')
    op.drop_index(op.f('ix_asistencia_personal_salida_en'), table_name='asistencia_personal')
    op.drop_index(op.f('ix_asistencia_personal_justificado'), table_name='asistencia_personal')
    op.drop_index(op.f('ix_asistencia_personal_fecha'), table_name='asistencia_personal')
    op.drop_index(op.f('ix_asistencia_personal_estado'), table_name='asistencia_personal')
    op.drop_index(op.f('ix_asistencia_personal_entrada_en'), table_name='asistencia_personal')
    op.drop_table('asistencia_personal')
    op.drop_index(op.f('ix_arqueos_sede_id'), table_name='arqueos')
    op.drop_index(op.f('ix_arqueos_mes'), table_name='arqueos')
    op.drop_index(op.f('ix_arqueos_elaborado_por'), table_name='arqueos')
    op.drop_index(op.f('ix_arqueos_anio'), table_name='arqueos')
    op.drop_table('arqueos')
    op.drop_index(op.f('ix_alumnos_tutor_id'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_sede_id'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_nombres'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_fecha_nacimiento'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_documento'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_codigo'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_apellidos'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_activo'), table_name='alumnos')
    op.drop_table('alumnos')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_sede_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_roles_permisos_rol_id'), table_name='roles_permisos')
    op.drop_index(op.f('ix_roles_permisos_permiso_id'), table_name='roles_permisos')
    op.drop_table('roles_permisos')
    op.drop_index(op.f('ix_precios_turnos_turno_id'), table_name='precios_turnos')
    op.drop_index(op.f('ix_precios_turnos_gestion'), table_name='precios_turnos')
    op.drop_index(op.f('ix_precios_turnos_categoria_pago_id'), table_name='precios_turnos')
    op.drop_table('precios_turnos')
    op.drop_index(op.f('ix_grupos_sede_id'), table_name='grupos')
    op.drop_index(op.f('ix_grupos_nombre'), table_name='grupos')
    op.drop_index(op.f('ix_grupos_gestion'), table_name='grupos')
    op.drop_index(op.f('ix_grupos_activo'), table_name='grupos')
    op.drop_table('grupos')
    op.drop_index(op.f('ix_cursos_extra_sede_id'), table_name='cursos_extra')
    op.drop_index(op.f('ix_cursos_extra_nombre'), table_name='cursos_extra')
    op.drop_table('cursos_extra')
    op.drop_index(op.f('ix_categorias_nombre'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_familia_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_turnos_nombre'), table_name='turnos')
    op.drop_table('turnos')
    op.drop_index(op.f('ix_tokens_revocados_tipo'), table_name='tokens_revocados')
    op.drop_index(op.f('ix_tokens_revocados_jti'), table_name='tokens_revocados')
    op.drop_table('tokens_revocados')
    op.drop_index(op.f('ix_sedes_codigo'), table_name='sedes')
    op.drop_table('sedes')
    op.drop_index(op.f('ix_roles_nombre'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permisos_vista'), table_name='permisos')
    op.drop_index(op.f('ix_permisos_accion'), table_name='permisos')
    op.drop_table('permisos')
    op.drop_index(op.f('ix_horarios_nombre'), table_name='horarios')
    op.drop_table('horarios')
    op.drop_index(op.f('ix_familias_nombre'), table_name='familias')
    op.drop_table('familias')
    op.drop_index(op.f('ix_categorias_pago_nombre'), table_name='categorias_pago')
    op.drop_table('categorias_pago')
    # ### end Alembic commands ###
