"""Actualizar campos de inscripcion

Revision ID: 9f85cf890246
Revises: 746a3d30f79a
Create Date: 2025-12-11 08:04:55.078939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9f85cf890246'
down_revision: Union[str, None] = '746a3d30f79a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumnos', sa.Column('direccion_domicilio', sa.Text(), nullable=True))
    op.add_column('alumnos', sa.Column('contacto_emergencia_nombre', sa.String(length=150), nullable=True))
    op.add_column('alumnos', sa.Column('contacto_emergencia_telefono', sa.String(length=20), nullable=True))
    op.add_column('alumnos', sa.Column('familiares_autorizados_recogo', sa.Text(), nullable=True))
    op.add_column('alumnos', sa.Column('familiares_en_casa', sa.Text(), nullable=True))
    op.add_column('alumnos', sa.Column('familiar_mas_apego', sa.String(length=100), nullable=True))
    op.add_column('alumnos', sa.Column('edad_levantarse_meses', sa.Integer(), nullable=True))
    op.add_column('alumnos', sa.Column('sintomas_denticion', sa.Text(), nullable=True))
    op.add_column('alumnos', sa.Column('problemas_succion_masticacion', sa.Text(), nullable=True))
    op.add_column('alumnos', sa.Column('transicion_alimentacion_solida', sa.Text(), nullable=True))
    op.add_column('alumnos', sa.Column('respuesta_problemas_comer', sa.Text(), nullable=True))
    op.add_column('alumnos', sa.Column('lugar_sueno', sa.String(length=100), nullable=True))
    op.add_column('alumnos', sa.Column('co_sleeping_bebe_edad', sa.String(length=100), nullable=True))
    op.add_column('alumnos', sa.Column('momento_problemas_sueno', sa.String(length=50), nullable=True))
    op.add_column('alumnos', sa.Column('respuesta_problemas_sueno', sa.Text(), nullable=True))
    op.add_column('alumnos', sa.Column('otros_habitos_sueno', sa.Text(), nullable=True))




    # ### end Alembic commands ###
