# app/kernel/domain/auditoria/ports.py
from __future__ import annotations
from typing import Protocol, Sequence, Optional
from datetime import datetime
from .auditoria_accion_entidad import AuditoriaAccion

class IAuditoriaAccionRepo(Protocol):
    async def registrar(self, ev: AuditoriaAccion) -> None: ...
    async def listar_por_usuario(self, usuario_id: int, *, limit: int = 100, offset: int = 0) -> Sequence[AuditoriaAccion]: ...
    async def listar_por_sede(self, sede_id: int, *, desde: Optional[datetime] = None, hasta: Optional[datetime] = None, limit: int = 100, offset: int = 0) -> Sequence[AuditoriaAccion]: ...
    async def listar_por_entidad(self, entidad: str, *, entidad_id: Optional[str] = None, limit: int = 100, offset: int = 0) -> Sequence[AuditoriaAccion]: ...
    async def listar_por_accion(self, accion: str, *, limit: int = 100, offset: int = 0) -> Sequence[AuditoriaAccion]: ...
