# app/kernel/domain/academico/ports.py
"""
Puertos (Protocols) para los repositorios del módulo académico.

Define los contratos que deben cumplir los repositorios concretos.
"""
from typing import Protocol, Sequence, Any, Optional
from datetime import date

class IHorarioRepository(Protocol):
    """Contrato para repositorio de horarios."""
    async def get(self, id_: int) -> Any: ...
    async def one(self, *, where: Any) -> Any: ...
    async def list(self, *, where: Any | None = None) -> Sequence[Any]: ...
    async def create(self, entidad: Any) -> Any: ...
    async def update(self, id_: int, data: dict) -> None: ...   
    async def delete(self, id_: int) -> None: ...
    async def exists_nombre_ci(self, *, nombre: str, excluir_id: Optional[int] = None) -> bool: ...


class IGrupoRepository(Protocol):
    """Contrato para repositorio de grupos."""
    async def get(self, id_: int) -> Any: ...
    async def one(self, *, where: Any) -> Any: ...
    async def list(self, *, where: Any | None = None) -> Sequence[Any]: ...
    async def list_by_sede(self, sede_id: int) -> Sequence[Any]: ...
    async def list_by_sede_gestion(self, sede_id: int, gestion: int) -> Sequence[Any]: ...
    async def list_activos_by_sede(self, sede_id: int) -> Sequence[Any]: ...
    async def create(self, entidad: Any) -> Any: ...
    async def update(self, id_: int, data: dict) -> None: ...
    async def soft_delete(self, id_: int) -> None: ...
    async def exists_letra_en_sede_gestion(self, *, sede_id: int, letra: str, gestion: int) -> bool: ...


class IParaleloRepository(Protocol):
    """Contrato para repositorio de paralelos."""
    async def get(self, id_: int) -> Any: ...
    async def one(self, *, where: Any) -> Any: ...
    async def list(self, *, where: Any | None = None) -> Sequence[Any]: ...
    async def list_by_grupo(self, grupo_id: int) -> Sequence[Any]: ...
    async def create(self, entidad: Any) -> Any: ...
    async def update(self, id_: int, data: dict) -> None: ...
    async def delete(self, id_: int) -> None: ...

class IHorarioParaleloRepository(Protocol):
    """Contrato para repositorio de horarios-paralelos."""
    async def get(self, id_: int) -> Any: ...
    async def one(self, *, where: Any) -> Any: ...
    async def list(self, *, where: Any | None = None) -> Sequence[Any]: ...
    async def list_by_paralelo(self, paralelo_id: int) -> Sequence[Any]: ...
    async def list_vigentes_by_paralelo(self, paralelo_id: int, fecha: date | None = None) -> Sequence[Any]: ...
    async def create(self, entidad: Any) -> Any: ...
    async def update(self, id_: int, data: dict) -> None: ...
    async def delete(self, id_: int) -> None: ...

class IParaleloProfesorRepository(Protocol):
    """Contrato para repositorio de paralelos-profesores."""
    async def get(self, id_: int) -> Any: ...
    async def one(self, *, where: Any) -> Any: ...
    async def list(self, *, where: Any | None = None) -> Sequence[Any]: ...
    async def list_by_paralelo(self, paralelo_id: int) -> Sequence[Any]: ...
    async def list_by_profesor(self, profesor_id: int) -> Sequence[Any]: ...
    async def list_vigentes_by_paralelo(self, paralelo_id: int, fecha: date | None = None) -> Sequence[Any]: ...
    async def list_vigentes_by_profesor(self, profesor_id: int, fecha: date | None = None) -> Sequence[Any]: ...
    async def create(self, entidad: Any) -> Any: ...
    async def update(self, id_: int, data: dict) -> None: ...
    async def delete(self, id_: int) -> None: ...
