from __future__ import annotations
from typing import Protocol, Sequence, Any
from datetime import date
from decimal import Decimal

# Entidades del dominio (tipos nominales)
from app.kernel.domain.inventario.familia_entidad import Familia
from app.kernel.domain.inventario.categoria_entidad import Categoria
from app.kernel.domain.inventario.item_entidad import Item
from app.kernel.domain.inventario.item_atributo_entidad import ItemAtributo
from app.kernel.domain.inventario.stock_sede_entidad import StockSede
from app.kernel.domain.inventario.movimiento_stock_entidad import MovimientoStock
from app.kernel.domain.inventario.prestamo_uniforme_entidad import PrestamoUniforme
from app.kernel.domain.inventario.alerta_stock_entidad import AlertaStock
from app.kernel.domain.inventario.alerta_vencimiento_entidad import AlertaVencimiento

# Repositorios (puertos) — Protocol definen contrato que cumplen los adapters SQLAlchemy
class IFamiliasRepo(Protocol):
    async def get(self, id_: int) -> Familia | None: ...
    async def one(self, *, where: Any) -> Familia | None: ...
    async def list(self, *, where: Any | None = None) -> Sequence[Familia]: ...
    async def create(self, entidad: Any) -> Familia: ...
    async def update(self, id_: int, data: dict) -> None: ...
    async def delete(self, id_: int) -> None: ...

class ICategoriasRepo(Protocol):
    async def get(self, id_: int) -> Categoria | None: ...
    async def one(self, *, where: Any) -> Categoria | None: ...
    async def list(self, *, where: Any | None = None) -> Sequence[Categoria]: ...
    async def create(self, entidad: Any) -> Categoria: ...
    async def update(self, id_: int, data: dict) -> None: ...
    async def delete(self, id_: int) -> None: ...

class IItemsRepo(Protocol):
    async def get(self, id_: int) -> Item | None: ...
    async def one(self, *, where: Any) -> Item | None: ...
    async def list(self, *, where: Any | None = None) -> Sequence[Item]: ...
    async def create(self, entidad: Any) -> Item: ...
    async def update(self, id_: int, data: dict) -> None: ...
    async def delete(self, id_: int) -> None: ...

class IItemsAtributosRepo(Protocol):
    async def list(self, *, where: Any | None = None) -> Sequence[ItemAtributo]: ...
    async def create(self, entidad: Any) -> ItemAtributo: ...

class IStockSedeRepo(Protocol):
    async def one(self, *, where: Any) -> StockSede | None: ...
    async def list(self, *, where: Any | None = None) -> Sequence[StockSede]: ...
    async def create(self, entidad: Any) -> StockSede: ...
    async def update(self, id_: int, data: dict) -> None: ...
    # Métodos semánticos recomendados
    async def list_por_sede(self, sede_id: int) -> Sequence[StockSede]: ...
    async def get_por_item_sede(self, item_id: int, sede_id: int) -> StockSede | None: ...
    async def upsert_minimo(self, item_id: int, sede_id: int, minimo: float) -> StockSede | None: ...

class IMovimientosStockRepo(Protocol):
    async def list(self, *, where: Any | None = None) -> Sequence[MovimientoStock]: ...
    async def create(self, entidad: Any) -> MovimientoStock: ...
    # Método semántico
    async def list_por_item(self, item_id: int) -> Sequence[MovimientoStock]: ...

class IPrestamosUniformesRepo(Protocol):
    async def get(self, id_: int) -> PrestamoUniforme | None: ...
    async def list(self, *, where: Any | None = None) -> Sequence[PrestamoUniforme]: ...
    async def create(self, entidad: Any) -> PrestamoUniforme: ...
    async def update(self, id_: int, data: dict) -> None: ...

class IAlertasStockRepo(Protocol):
    async def one(self, *, where: Any) -> AlertaStock | None: ...
    async def list(self, *, where: Any | None = None) -> Sequence[AlertaStock]: ...
    async def create(self, entidad: Any) -> AlertaStock: ...
    async def update(self, id_: int, data: dict) -> None: ...

class IAlertasVencimientoRepo(Protocol):
    async def one(self, *, where: Any) -> AlertaVencimiento | None: ...
    async def list(self, *, where: Any | None = None) -> Sequence[AlertaVencimiento]: ...
    async def create(self, entidad: Any) -> AlertaVencimiento: ...
    async def update(self, id_: int, data: dict) -> None: ...

# Puertos de servicios de dominio (si necesitases abstraer lógica fuera de repos)
class IGeneradorSKU(Protocol):
    def generar(self, nombre: str, atributos: list[tuple[str, str]], prefijo: str | None = None, maxlen: int = 50) -> str: ...

class IClock(Protocol):
    def hoy(self) -> date: ...
